// propertyData.js
// Last verified: April 13, 2026

export const ALL_PROPERTIES = [
  {
    id: "prop_006",
    address: "10272 Whitetail Cir",
    city: "Fishers",
    price: 525000,
    beds: 4,
    baths: 2.5,
    sqft: 2737,
    garage: 3,
    yearBuilt: 1996,
    hoaAnnual: 515,
    lotSize: 0.38,
    basement: "None",
    neighborhood: "Woods Edge (Part of Windermere)",
    neighborhoodSummary: "A sub-neighborhood within the 9-subdivision Windermere master community near Geist Reservoir, where pool access, tennis courts, and clubhouse are confirmed available to Woods Edge residents through the Windermere master HOA. Pool: Confirmed Yes (Windermere master HOA-included) — pool access confirmed for Woods Edge residents specifically; home count for Woods Edge is unknown, though the broader Windermere community spans hundreds of homes across 9 sections.",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Sold",
    daysOnMarket: "Active",
    walkScore: 8,
    bikeScore: 36,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/10272-Whitetail-Cir-Fishers-IN-46037/73252526_zpid/",
    notes: "Windermere golf community.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 192,
    imageUrl: "https://ap.rdcpix.com/81fb77bb2d114fa4a445c4efb076fe09l-m3444053804rd-w1280_h960.webp",
    latitude: 39.93710973008341,
    longitude: -85.98644956200211,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: false, restaurants: false, communityEvents: true },
    history: { daysOnMarket: 34, lastPriceChange: null, priceChanges: [], views: 0 },
    listingDate: "2025-10-15",
  },
  {
    id: "prop_009",
    address: "10747 Red Pine Dr",
    city: "Fishers",
    price: 475000,
    beds: 5,
    baths: 3.5,
    sqft: 4323,
    garage: 3,
    yearBuilt: 1998,
    hoaAnnual: 0,
    lotSize: 0.32,
    basement: "Finished",
    neighborhood: "Pine Bluff Overlook",
    neighborhoodSummary: "A self-managed neighborhood in northern Fishers with $360/year dues (confirmed for 2026), focused on architectural review and covenant governance rather than shared amenities. Pool: Confirmed No — the official HOA website lists no pool or recreational amenities of any kind; home count is not published by the HOA.",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 8,
    bikeScore: 55,
    hasNeighborhoodPool: false,
    zillowLink: "https://www.zillow.com/homedetails/10747-Red-Pine-Dr-Fishers-IN-46037/73228273_zpid/",
    notes: "5 bedroom home with finished walkout basement. Near Windermere golf course.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2025-10-31", price: 500000, event: "Listed" },
      { date: "2026-01-21", oldPrice: 500000, newPrice: 475000 },
    ],
    favorite: false,
    pricePerSqft: 110,
    imageUrl: "https://photos.zillowstatic.com/fp/025cf54831f2bcfc22eca5aac5dda275-cc_ft_1152.webp",
    latitude: 39.94267103088205,
    longitude: -85.99661627734538,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: false, restaurants: false, communityEvents: true },
    history: { daysOnMarket: 144, lastPriceChange: "2026-01-21", priceChanges: [], views: 0 },
    listingDate: "2025-10-31",
  },
  {
    id: "prop_010",
    address: "11987 Bird Key Blvd",
    city: "Fishers",
    price: 578000,
    beds: 4,
    baths: 3.5,
    sqft: 3618,
    garage: 2,
    yearBuilt: 2004,
    hoaAnnual: 768,
    lotSize: 0.27,
    basement: "Finished",
    neighborhood: "Rolling Knoll",
    neighborhoodSummary: "A Kirkpatrick-managed community of 172 homes (confirmed via management company records) with a community pool, playground, and amenity center. Pool: Confirmed Yes (HOA-included); $750/year HOA is the second-highest in the file, reflecting the full amenity package.",
    schools: "Hamilton Southeastern",
    commuteHusband: 35,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 14,
    bikeScore: 53,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/11987-Bird-Key-Blvd-Fishers-IN-46037/73249194_zpid/",
    notes: "Brick home with finished basement.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-03-19", oldPrice: 584000, newPrice: 578000 }],
    favorite: false,
    pricePerSqft: 160,
    imageUrl: "https://ssl.cdn-redfin.com/photo/147/bigphoto/902/22082902_0.jpg",
    latitude: 39.96291071302564,
    longitude: -85.969532246657,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 55, lastPriceChange: "2026-03-19", priceChanges: [], views: 0 },
    listingDate: "2026-01-26",
  },
  {
    id: "prop_012",
    address: "12997 Bartlett Dr",
    city: "Fishers",
    price: 474900,
    beds: 5,
    baths: 3,
    sqft: 4042,
    garage: 3,
    yearBuilt: 2007,
    hoaAnnual: 610,
    lotSize: 0.23,
    basement: "None",
    neighborhood: "Tanglewood",
    neighborhoodSummary: "A multi-phase Fishers neighborhood managed by Sentry Management with a confirmed community pool, park, playground, and trails at $610/year HOA. Pool: Confirmed Yes (HOA-included); total home count across all phases is not published by the HOA and should be verified via Hamilton County parcel data.",
    schools: "Hamilton Southeastern",
    commuteHusband: 32,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 12,
    bikeScore: 54,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/12997-Bartlett-Dr-Fishers-IN-46037/99124508_zpid/",
    notes: "Large 5BR home in Tanglewood.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2025-08-07", oldPrice: 488900, newPrice: 469900 },
      { date: "2025-10-03", oldPrice: 469900, newPrice: 469900 },
      { date: "2026-02-12", price: 474900, event: "Relisted" },
    ],
    favorite: false,
    pricePerSqft: 117,
    imageUrl: "https://images-listings.coldwellbanker.com/IN_MIBOR/22/08/34/80/_P/22083480_P00.jpg",
    latitude: 39.985,
    longitude: -86.0125,
    amenities: { parks: true, trails: false, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 48, lastPriceChange: "2026-02-12", priceChanges: [], views: 0 },
    listingDate: "2026-02-12",
  },
  {
    id: "prop_014",
    address: "10480 Creektree Ln",
    city: "Fishers",
    price: 615000,
    beds: 4,
    baths: 3,
    sqft: 4217,
    garage: 3,
    yearBuilt: 2003,
    hoaAnnual: 535,
    lotSize: 0.29,
    basement: "Finished",
    neighborhood: "Rosewood (Part of Parkshore POA)",
    neighborhoodSummary: "One of four neighborhoods (Plantana, Auburn Springs, Rosewood, Northpoint) under the Parkshore Property Owners Association, which collectively administers a pool, park, playground, tennis courts, basketball courts, and a jogging path at $535/year for 2026. Pool: Confirmed Yes (Parkshore POA-included); the number of homes in the Rosewood section specifically is not published separately — the POA covers all four neighborhoods collectively.",
    schools: "Hamilton Southeastern",
    commuteHusband: 40,
    status: "Sold",
    daysOnMarket: "Active",
    walkScore: 8,
    bikeScore: 53,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/10480-Creektree-Ln-Fishers-IN-46038/73248900_zpid/",
    notes: "Rosewood home sold April 1, 2026.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-02-23", price: 600000, event: "Listed" },
      { date: "2026-04-01", oldPrice: 600000, newPrice: 615000, event: "Sold" },
    ],
    favorite: false,
    pricePerSqft: 146,
    imageUrl: "https://cflare.smarteragent.com/rest/Resizer?sig_id=69&quality=0.8&url=https://storage.googleapis.com/slp5-stream-listing-media-prod/MLSGrid/190/22068876/photo/media/0_4261413115053874048.jpg&width=1000",
    latitude: 39.983606286476395,
    longitude: -85.98258444665584,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: true, restaurants: false, communityEvents: false },
    history: { daysOnMarket: 45, lastPriceChange: "2026-04-01", priceChanges: [], views: 0 },
    listingDate: "2026-02-27",
  },
  {
    id: "prop_015",
    address: "10236 Bent Tree Ln",
    city: "Fishers",
    price: 615000,
    beds: 4,
    baths: 2.5,
    sqft: 4209,
    garage: 3,
    yearBuilt: 1995,
    hoaAnnual: 552,
    lotSize: 0.31,
    basement: "Finished",
    neighborhood: "Woods Edge (Part of Windermere)",
    neighborhoodSummary: "A sub-neighborhood within the 9-subdivision Windermere master community near Geist Reservoir, where pool access, tennis courts, and clubhouse are confirmed available to Woods Edge residents through the Windermere master HOA. Pool: Confirmed Yes (Windermere master HOA-included) — pool access confirmed for Woods Edge residents specifically; home count for Woods Edge is unknown, though the broader Windermere community spans hundreds of homes across 9 sections.",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 13,
    bikeScore: 37,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/10236-Bent-Tree-Ln-Fishers-IN-46037/73252130_zpid/",
    notes: "Holiday lights street home.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-02-12", price: 630900, event: "Listed" },
      { date: "2026-03-13", oldPrice: 630900, newPrice: 619900 },
    ],
    favorite: false,
    pricePerSqft: 147,
    imageUrl: "https://cdn.listingphotos.sierrastatic.com/pics3x/v1772489899/203/203_22082152_01.jpg",
    latitude: 39.936641852261445,
    longitude: -85.98868479083804,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: true, restaurants: false, communityEvents: true },
    history: { daysOnMarket: 24, lastPriceChange: "2026-03-13", priceChanges: [], views: 0 },
    listingDate: "2026-02-12",
  },
  {
    id: "prop_016",
    address: "12033 Flintstone Ct",
    city: "Fishers",
    price: 495000,
    beds: 5,
    baths: 3,
    sqft: 3382,
    garage: 2,
    yearBuilt: 2000,
    hoaAnnual: 335,
    lotSize: 0.24,
    basement: "Finished",
    neighborhood: "Sandstone Lakes (Part of Sandstone)",
    neighborhoodSummary: "One section of the seven-section Sandstone master community (1,000+ total homes), with 370 homes in the Lakes section confirmed via Estridge builder data and the official Sandstone HOA website, featuring a pool, clubhouse, park, playground, and 21 retention ponds at $335/year — the lowest HOA fee with pool access in the file. Pool: Confirmed Yes (HOA-included).",
    schools: "Hamilton Southeastern",
    commuteHusband: 35,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 29,
    bikeScore: 59,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/12033-Flint-Stone-Ct-Fishers-IN-46037/73274763_zpid/",
    notes: "Move-in ready Sandstone Lakes home.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-03-06", price: 510000, event: "Listed" },
      { date: "2026-03-16", oldPrice: 510000, newPrice: 495000 },
      { date: "2026-03-23", event: "Pending" },
    ],
    favorite: false,
    pricePerSqft: 146,
    imageUrl: "https://photos.talktotucker.com/medium/mibor/22087220/12033-flint-stone-court-fishers-46037-ccb528d0-b8b7-4b83-ba0b-dfa5c931ccb8-0.jpeg",
    latitude: 39.96388970331086,
    longitude: -85.94847674665694,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: true, restaurants: false, communityEvents: false },
    history: { daysOnMarket: 17, lastPriceChange: "2026-03-16", priceChanges: [], views: 0 },
    listingDate: "2026-03-06",
  },
  {
    id: "prop_017",
    address: "9943 Deering St",
    city: "Fishers",
    price: 499000,
    beds: 4,
    baths: 2.5,
    sqft: 3830,
    garage: 2,
    yearBuilt: 1996,
    hoaAnnual: 400,
    lotSize: 0.27,
    basement: "Finished",
    neighborhood: "Spyglass Hill",
    neighborhoodSummary: "A well-documented community with its own HOA website confirming an Olympic-size pool plus a kids pool and grill area, open Memorial Day through Labor Day to residents with a valid pool pass. Pool: Confirmed Yes (HOA-included) — confirmed directly from the official Spyglass Hill HOA website; home count is not published on the HOA site.",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 15,
    bikeScore: 57,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/9943-Deering-St-Fishers-IN-46037/73275377_zpid/",
    notes: "Spyglass Hill home built in 1996.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-03-13", price: 499000, event: "Listed" },
      { date: "2026-03-27", event: "Pending" },
      { date: "2026-04-01", event: "Back to Active" },
    ],
    favorite: false,
    pricePerSqft: 130,
    imageUrl: "https://ssl.cdn-redfin.com/photo/147/bigphoto/523/22088523_0.jpg",
    latitude: 39.94736887365393,
    longitude: -85.99192700432972,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: true, restaurants: false, communityEvents: false },
    history: { daysOnMarket: 19, lastPriceChange: "2026-04-01", priceChanges: [], views: 0 },
    listingDate: "2026-03-13",
  },
  {
    id: "prop_018",
    address: "13374 Landwood Dr",
    city: "Fishers",
    price: 640000,
    beds: 4,
    baths: 3.5,
    sqft: 4276,
    garage: 3,
    yearBuilt: 2000,
    hoaAnnual: 475,
    lotSize: 0.28,
    basement: "Finished",
    neighborhood: "Links at Gray Eagle (Part of Gray Eagle)",
    neighborhoodSummary: "A golf-oriented community within the two-section Gray Eagle HOA (Links + The Woods) at $475/year, with trails, playground, basketball, tennis, and pickleball included in dues. Pool: Yes (separate paid membership) — Gray Eagle Pool is an independently operated, open-membership facility available to all Hamilton County residents; confirmed explicitly not included in the $475 HOA dues.",
    schools: "Hamilton Southeastern",
    commuteHusband: 36,
    status: "Sold",
    daysOnMarket: "Active",
    walkScore: 12,
    bikeScore: 52,
    hasNeighborhoodPool: false,
    zillowLink: "https://www.zillow.com/homedetails/13374-Landwood-Dr-Fishers-IN-46038/349258174_zpid/",
    notes: "Gray Eagle golf community home.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-03-13", price: 640000, event: "Listed" },
      { date: "2026-03-16", event: "Pending" },
      { date: "2020-01-21", price: 387400, event: "Sold" },
    ],
    favorite: false,
    pricePerSqft: 150,
    imageUrl: "https://photos.talktotucker.com/medium/mibor/22088967/13374-landwood-drive-fishers-46037-0bb02b16-c500-4264-9e68-ec4d35ad4c26-0.jpeg",
    latitude: 39.96223066123813,
    longitude: -85.92545233131347,
    coordinateVerified: false,
    amenities: { parks: true, trails: true, shopping: true, restaurants: false, communityEvents: true },
    history: { daysOnMarket: 3, lastPriceChange: "2026-03-16", priceChanges: [], views: 0 },
    listingDate: "2026-03-13",
  },
  {
    id: "prop_019",
    address: "11008 Stratford Way",
    city: "Fishers",
    price: 499900,
    beds: 4,
    baths: 2.5,
    sqft: 3138,
    garage: 2,
    yearBuilt: 1992,
    hoaAnnual: 546,
    lotSize: 0.27,
    basement: "Finished",
    neighborhood: "Oxford Park",
    neighborhoodSummary: "An Estridge-built neighborhood from the late 1980s to early 1990s with tennis courts, a park, playground, and walking trails at $546/year HOA. Pool: Confirmed No — official MIBOR listing confirms HOA amenities include only entrance common, insurance, maintenance, park/playground, management, snow removal, and tennis courts; no pool listed.",
    schools: "Hamilton Southeastern",
    commuteHusband: 32,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 9,
    bikeScore: 54,
    hasNeighborhoodPool: false,
    zillowLink: "https://www.zillow.com/homedetails/11008-Stratford-Way-Fishers-IN-46038/73227768_zpid/",
    notes: "4-season room, finished basement with 30x20 playroom.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-03-09", price: 499900, event: "Listed" }],
    favorite: false,
    pricePerSqft: 159,
    imageUrl: "https://ap.rdcpix.com/d32bcc1af93adb290455af9f238ef150l-m1205120643rd-w960_h720.webp",
    latitude: 39.947588248037,
    longitude: -86.05841686200147,
    amenities: { parks: true, trails: true, shopping: false, restaurants: false, communityEvents: false },
    history: { daysOnMarket: 24, lastPriceChange: null, priceChanges: [], views: 0 },
    listingDate: "2026-03-09",
  },
  {
    id: "prop_020",
    address: "10970 Andrews Pl",
    city: "Fishers",
    price: 580000,
    beds: 5,
    baths: 4,
    sqft: 4316,
    garage: 2,
    yearBuilt: 1995,
    hoaAnnual: 860,
    lotSize: 0.31,
    basement: "Finished",
    neighborhood: "Walnut Creek",
    neighborhoodSummary: "A small, self-described community with approximately 162 residents per Nextdoor (no HOA-published home count available) and a strong community identity anchored by its Rambler newsletter and active events calendar; HOA dues are $430 semi-annually ($860/year). Pool: Confirmed No — Walnut Creek does not appear on the Fishers neighborhoods with pool directory, and HOA fee inclusions confirmed as trash/snow/maintenance only across multiple listing sources.",
    schools: "Hamilton Southeastern",
    commuteHusband: 34,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 12,
    bikeScore: 53,
    hasNeighborhoodPool: false,
    zillowLink: "https://www.zillow.com/homedetails/10970-Andrews-Pl-Fishers-IN-46037/73267537_zpid/",
    notes: "Corner lot in Walnut Creek with finished basement.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-03-19", price: 580000, event: "Listed" }],
    favorite: false,
    pricePerSqft: 134,
    imageUrl: "https://photos.talktotucker.com/medium/mibor/22089401/10970-andrews-place-fishers-46037-f55b4e71-b410-4df8-afd3-31606ac3fdd2-0.jpeg",
    latitude: 39.947017,
    longitude: -85.998194,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: false },
    history: { daysOnMarket: 2, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-03-19",
  },
  {
    id: "prop_021",
    address: "11750 Belle Plaine Blvd",
    city: "Fishers",
    price: 650000,
    beds: 4,
    baths: 4,
    sqft: 4136,
    garage: 2,
    yearBuilt: 2001,
    hoaAnnual: 750,
    lotSize: 0.47,
    basement: "Finished",
    neighborhood: "Rolling Knoll",
    neighborhoodSummary: "A Kirkpatrick-managed community of 172 homes (confirmed via management company records) with a community pool, playground, and amenity center. Pool: Confirmed Yes (HOA-included); $750/year HOA is the second-highest in the file, reflecting the full amenity package.",
    schools: "Hamilton Southeastern",
    commuteHusband: 34,
    status: "Sold",
    daysOnMarket: "Active",
    walkScore: 15,
    bikeScore: 59,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/11750-Belle-Plaine-Blvd-Fishers-IN-46037/73249036_zpid/",
    notes: "Premium corner lot on nearly half an acre in Rolling Knoll.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 157,
    imageUrl: "https://images.remax.com/webapi-properties-mibor3/6401ccbfca979759a6af7faf9ca49e15d85886e9-3-original.jpeg",
    latitude: 39.959441810293235,
    longitude: -85.9691714908367,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 14, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-03-18",
  },
  {
    id: "prop_022",
    address: "12992 Minden Dr",
    city: "Fishers",
    price: 575000,
    beds: 5,
    baths: 4,
    sqft: 4346,
    garage: 2,
    yearBuilt: 2011,
    hoaAnnual: 650,
    lotSize: 0.21,
    basement: "Finished",
    neighborhood: "Saxony",
    neighborhoodSummary: "A Planned Urban Development spanning multiple boroughs with a confirmed community pool, Saxony Lake, two parks, two playgrounds, and walkable access to restaurants, a donut shop, post office, gym, and hair salon — the only genuinely walkable neighborhood in the file. Pool: Confirmed Yes (HOA-included); the PUD spans hundreds of homes across six boroughs and a single home count is not meaningful without specifying the borough.",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Pending",
    daysOnMarket: "New",
    walkScore: 27,
    bikeScore: 59,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/12992-Minden-Dr-Fishers-IN-46037/120230383_zpid/",
    notes: "Walkable to community pool, 2 playgrounds, Witten Park, trails, Saxony Pizzeria & Boom Town Donuts. New staircase, carpet, appliances (March 2026), new roof (2020).",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-03-20", price: 575000, event: "Listed" }],
    favorite: false,
    pricePerSqft: 132,
    imageUrl: "https://photos.talktotucker.com/medium/mibor/22087784/12992-minden-drive-fishers-46037-3d2001ae-1f75-4dce-a851-e64626860522-0.jpeg",
    latitude: 39.97947421767583,
    longitude: -85.92583729083555,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 5, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-03-20",
  },
  {
    id: "prop_023",
    address: "14211 Monarchy Ln",
    city: "Fishers",
    price: 535000,
    beds: 4,
    baths: 4,
    sqft: 3909,
    garage: 2,
    yearBuilt: 2003,
    hoaAnnual: 500,
    lotSize: 0.25,
    basement: "Finished",
    neighborhood: "Royalwood",
    neighborhoodSummary: "A large community spanning four sections (Royalwood, Trails, South, and Lakes) with its own HOA website, a community pool shared across all four sections, clubhouse, basketball courts, and paved nature paths at $500/year. Pool: Confirmed Yes (HOA-included) — pool serves all four sections of the Royalwood community; total home count across all sections is estimated at 600-700 but not confirmed by a primary source.",
    schools: "Hamilton Southeastern",
    commuteHusband: 31,
    status: "Pending",
    daysOnMarket: "New",
    walkScore: 44,
    bikeScore: 68,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/14211-Monarchy-Ln-Fishers-IN-46038/73220549_zpid/",
    notes: "Backs to nature preserve with access to Geist-Greenway. Finished basement with 9-ft ceilings, rec room with bar, Murphy bed in guest room. Outdoor entertaining with pergola deck, stamped concrete patio, built-in gas firepit & grill.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-03-20", price: 535000, event: "Listed" },
      { date: "2026-03-27", event: "Pending" },
    ],
    favorite: false,
    pricePerSqft: 137,
    imageUrl: "https://images.remax.com/webapi-properties-mibor3/1f154c9422ded61447244cf10db9260dec536cc6-3-original.jpeg",
    latitude: 39.959724914832016,
    longitude: -85.91110298898539,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: false },
    history: { daysOnMarket: 7, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-03-20",
  },
  {
    id: "prop_024",
    address: "9767 Fortune Dr",
    city: "Fishers",
    price: 650000,
    beds: 4,
    baths: 3.5,
    sqft: 4340,
    garage: 3,
    yearBuilt: 1995,
    hoaAnnual: 860,
    lotSize: 0.42,
    basement: "Finished",
    neighborhood: "Walnut Creek",
    neighborhoodSummary: "A small, self-described community with approximately 162 residents per Nextdoor (no HOA-published home count available) and a strong community identity anchored by its Rambler newsletter and active events calendar; HOA dues are $430 semi-annually ($860/year). Pool: Confirmed No — Walnut Creek does not appear on the Fishers neighborhoods with pool directory, and HOA fee inclusions confirmed as trash/snow/maintenance only across multiple listing sources.",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 5,
    bikeScore: 45,
    hasNeighborhoodPool: false,
    zillowLink: "https://www.zillow.com/homedetails/9767-Fortune-Dr-Fishers-IN-46037/73267542_zpid/",
    notes: "Large lot with mature trees in Walnut Creek.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 150,
    imageUrl: "https://ssl.cdn-redfin.com/photo/147/bigphoto/129/22087129_0.jpg",
    latitude: 39.945815340643925,
    longitude: -85.99641988805293,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: false },
    history: { daysOnMarket: 24, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-03-04",
  },
  {
    id: "prop_025",
    address: "13867 Cold Spring Dr",
    city: "Fishers",
    price: 650000,
    beds: 4,
    baths: 4,
    sqft: 4310,
    garage: 2,
    yearBuilt: 2011,
    hoaAnnual: 1320,
    lotSize: 0.34,
    basement: "Finished",
    neighborhood: "Anderson Hall",
    neighborhoodSummary: "An Estridge-built community (2005-2015 era) with the highest HOA in the file at $1,320/year, covering a pool, Grand Hall clubhouse, playground, scenic ponds, and green space — pool membership is confirmed included in HOA dues. Pool: Confirmed Yes (HOA-included); home count is not published by the HOA and was not found in any primary source — should be verified via Hamilton County parcel data.",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Active",
    daysOnMarket: "New",
    walkScore: 2,
    bikeScore: 48,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/13867-Cold-Spring-Dr-Fishers-IN-46038/139014824_zpid/",
    notes: "Anderson Hall home with open floor plan, 9-ft ceilings, hardwood floors, granite counters, gas range, butler's pantry. Finished basement with 9-ft ceilings, half bath, and 25x30 playroom. Garage has 10ft extra depth. Corner lot across from community green space.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-04-02", price: 650000, event: "Listed" },
      { date: "2026-04-04", oldPrice: 650000, newPrice: 519900 },
    ],
    favorite: false,
    pricePerSqft: 121,
    imageUrl: "https://photos.zillowstatic.com/fp/030398cc4d89611c8017fca5752f6de0-cc_ft_1152.webp",
    latitude: 39.991398525055345,
    longitude: -85.97223098650771,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 1, lastPriceChange: "2026-04-04", priceChanges: [], views: 0 },
    listingDate: "2026-04-02",
  },
  {
    id: "prop_026",
    address: "13985 Royalwood Dr",
    city: "Fishers",
    price: 441900,
    beds: 4,
    baths: 2.5,
    sqft: 3920,
    garage: 2,
    yearBuilt: 1999,
    hoaAnnual: 500,
    lotSize: 0.33,
    basement: "Finished",
    neighborhood: "Royalwood",
    neighborhoodSummary: "A large community spanning four sections (Royalwood, Trails, South, and Lakes) with its own HOA website, a community pool shared across all four sections, clubhouse, basketball courts, and paved nature paths at $500/year. Pool: Confirmed Yes (HOA-included) — pool serves all four sections of the Royalwood community; total home count across all sections is estimated at 600-700 but not confirmed by a primary source.",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Sold",
    daysOnMarket: "New",
    walkScore: 46,
    bikeScore: 65,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/13985-Royalwood-Dr-Fishers-IN-46037/73250789_zpid/",
    notes: "Beautifully updated in Royalwood. Large 2-story foyer, private office with French doors and built-in bookshelves, 10-ft ceilings in great room, gas fireplace, updated custom kitchen with stainless appliances. Primary suite with vaulted ceilings. Finished basement. Large fenced backyard with patio. Mature trees. Community pool.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-04-03", price: 519900, event: "Listed" },
    ],
    favorite: false,
    pricePerSqft: 133,
    imageUrl: "https://ap.rdcpix.com/3f24341aa615497456df75252d06b36dl-m381649827rd-w960_h720.webp",
    latitude: 39.96032427280276,
    longitude: -85.91500858805222,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 1, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-04-03",
  },
  {
    id: "prop_027",
    address: "9923 Deering St",
    city: "Fishers",
    price: 489000,
    beds: 4,
    baths: 4,
    sqft: 3126,
    garage: 2,
    yearBuilt: 1996,
    hoaAnnual: 420,
    lotSize: 0.24,
    basement: "Finished",
    neighborhood: "Spyglass Hill",
    neighborhoodSummary: "A well-documented community with its own HOA website confirming an Olympic-size pool plus a kids pool and grill area, open Memorial Day through Labor Day to residents with a valid pool pass. Pool: Confirmed Yes (HOA-included) — confirmed directly from the official Spyglass Hill HOA website; home count is not published on the HOA site.",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 19,
    bikeScore: 57,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/9923-Deering-St-Fishers-IN-46037/99135148_zpid/",
    notes: "Close to Fishers District with shopping, dining and Topgolf. 4-season room, finished basement.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-04-09", price: 489000, event: "Listed" }],
    favorite: false,
    pricePerSqft: 156,
    imageUrl: "https://photos.zillowstatic.com/fp/4d7c66252202050f6bfe923af0aa3fc9-sc_1920_1280.webp",
    latitude: 39.94735678671617,
    longitude: -85.99246896106825,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: false },
    history: { daysOnMarket: 1, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-04-09",
  },
  {
    id: "prop_028",
    address: "9725 Covington Blvd",
    city: "Fishers",
    price: 495000,
    beds: 4,
    baths: 3,
    sqft: 3802,
    garage: 2,
    yearBuilt: 1995,
    hoaAnnual: 450,
    lotSize: 0.36,
    basement: "Finished",
    neighborhood: "Covington Estate",
    neighborhoodSummary: "An Estridge-built community with a confirmed 203 homes (cross-verified via builder records and Dwellane at approximately 220, a narrow variance likely reflecting phase boundaries), featuring a pool plus kiddie pool, tennis, basketball, playground, and the largest average lot size (0.4 acres) in the file at $450/year HOA. Pool: Confirmed Yes (HOA-included).",
    schools: "Hamilton Southeastern",
    commuteHusband: 34,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 44,
    bikeScore: 39,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/9725-Covington-Blvd-Fishers-IN-46037/73267646_zpid/",
    notes: "Mature, established neighborhood with community pool and tennis courts. Screened-in porch, fenced backyard. Roof replaced 2020.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-04-09", price: 495000, event: "Listed" }],
    favorite: true,
    pricePerSqft: 130,
    imageUrl: "https://photos.zillowstatic.com/fp/8c77d6400e447c66b0bd1f5aee4fcd9c-cc_ft_1152.webp",
    latitude: 39.92790234401471,
    longitude: -86.00629328805381,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: true, restaurants: true, communityEvents: true },
    history: { daysOnMarket: 1, lastPriceChange: "", priceChanges: [], views: 0 },
    listingDate: "2026-04-09",
  },
  {
    id: "prop_029",
    address: "10343 Waveland Cir",
    city: "Fishers",
    price: 479000,
    beds: 5,
    baths: 4,
    sqft: 4299,
    garage: 2,
    yearBuilt: 2003,
    hoaAnnual: 525,
    lotSize: 0.33,
    basement: "Finished",
    neighborhood: "Northpoint (Part of Parkshore POA)",
    neighborhoodSummary: "One of four neighborhoods under the Parkshore POA alongside Plantana, Auburn Springs, and Rosewood, sharing a pool, park, playground, tennis, basketball, and jogging path at $535/year for 2026. Pool: Confirmed Yes (Parkshore POA-included); the number of homes in the Northpoint section is not published separately — same structural note as Rosewood applies.",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Active",
    daysOnMarket: "New",
    walkScore: 5,
    bikeScore: 52,
    hasNeighborhoodPool: true,
    zillowLink: "https://www.zillow.com/homedetails/10343-Waveland-Cir-Fishers-IN-46038/94401497_zpid/",
    notes: "5BR/4BA in Northpoint on cul-de-sac. Largest lot in neighborhood. Finished basement with surround sound. Updated kitchen with marble countertops and ceramic backsplash. New tile in laundry/baths, new carpet on second floor. 2.5-car garage with 3ft bump-out. Front and back porches. Community pool, park, tennis, basketball courts, and jogging path.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-04-09", price: 479000, event: "Listed" },
    ],
    favorite: false,
    pricePerSqft: 111,
    imageUrl: "https://photos.zillowstatic.com/fp/179ac312b916cd058849cf9290d534ae-cc_ft_768.webp",
    latitude: 39.99314649292328,
    longitude: -85.98463559014357,
    coordinateVerified: true,
    amenities: { parks: true, trails: true, shopping: false, restaurants: false, communityEvents: false },
    history: { daysOnMarket: 4, lastPriceChange: null, priceChanges: [], views: 0 },
    listingDate: "2026-04-09",
  },
  {
  id: "prop_030",
  address: "9279 Oak Knoll Ln",
  city: "Fishers",
  price: 525000,
  beds: 4,
  baths: 2.5,
  sqft: 3901,
  garage: 2,
  yearBuilt: 1996,
  hoaAnnual: 528,
  lotSize: 0.3,
  basement: "Finished",
  neighborhood: "Delaware Pointe",
  neighborhoodSummary: "Delaware Pointe is a quiet, established subdivision in Fishers near I-69. The neighborhood is situated on a cul-de-sac street with a park and playground included in HOA amenities. Neighborhood connects to walking trails in multiple directions. Lantern Road Elementary School (rated A) serves this area. No community pool confirmed.",
  schools: "Hamilton Southeastern",
  commuteHusband: 36,
  status: "Active",
  daysOnMarket: "Active",
  walkScore: 6,
  bikeScore: 47,
  hasNeighborhoodPool: false,
  zillowLink: "https://www.zillow.com/homedetails/9279-Oak-Knoll-Ln-Fishers-IN-46037/73228044_zpid/",
  notes: "Beautifully updated 4-bed, 2.5-bath home in Delaware Pointe on a quiet cul-de-sac. Main level features a fireplace family room, formal dining with tray ceiling, private office with French doors, and updated kitchen with island and stainless appliances. Primary suite has walk-in closet, dual sinks, soaking tub, and full shower. Finished basement rec space. Recent updates: brand new roof, new carpet, new sump pump (2026), new oven/range (12/25), new front door (11/25). Side-load 2-car garage with attic storage. Deck and backyard. Trails accessible from neighborhood.",
  pros: [
    "Brand new roof and new carpet",
    "Finished basement rec space",
    "Private home office with French doors",
    "Updated kitchen with island and stainless appliances",
    "Quiet cul-de-sac with neighborhood park and walking trail access",
    "Side-load garage with attic storage",
  ],
  cons: [],
  priceHistory: [
    { date: "2026-04-16", price: 525000, event: "Listed" },
  ],
  favorite: false,
  pricePerSqft: 135,
  imageUrl: "https://photos.zillowstatic.com/fp/0cce1a342477febb57ec210d8a32d1c0-cc_ft_768.webp",
  latitude: 39.94346738850527,
  longitude: -86.00022266204736,
  amenities: {
    parks: true,
    trails: true,
    shopping: true,
    restaurants: true,
    communityEvents: false,
  },
  history: {
    daysOnMarket: 0,
    lastPriceChange: null,
    priceChanges: [],
    views: 346,
  },
  listingDate: "2026-04-16",
},
];
