// propertyData.js

export const ALL_PROPERTIES = [
  {
    id: "prop_004",
    address: "12880 Oxbridge Pl",
    city: "Fishers",
    price: 444900,
    beds: 3,
    baths: 2.5,
    sqft: 3430,
    garage: 2,
    yearBuilt: 2004,
    hoaAnnual: 696,
    lotSize: 0.25,
    basement: "Finished",
    neighborhood: "Avalon of Fishers",
    schools: "Hamilton Southeastern",
    commuteHusband: 37,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 8,
    bikeScore: 52,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.zillow.com/homedetails/12880-Oxbridge-Pl-Fishers-IN-46037/73219952_zpid/",
    notes: "Ranch with pond views and finished basement.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-01-15", oldPrice: 468900, newPrice: 444900 }],
    favorite: false,
    pricePerSqft: 130,
    imageUrl:
      "https://photos.zillowstatic.com/fp/fa5b10bf7e4e0e4faf2b98f0263609da-cc_ft_1152.webp",
    latitude: 39.97655133863871,
    longitude: -85.91614624665627,
    coordinateVerified: false, // TODO: Verify via Google Maps
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 89,
      lastPriceChange: "2026-01-15",
      priceChanges: [],
      views: 0,
    },
    listingDate: "2025-10-15",
  },

  {
    id: "prop_006",
    address: "10272 Whitetail Cir",
    city: "Fishers",
    price: 525000,
    beds: 4,
    baths: 2.5,
    sqft: 2737,
    garage: 2,
    yearBuilt: 2003,
    hoaAnnual: 0,
    lotSize: 0.38,
    basement: "None",
    neighborhood: "Woods Edge At Windermere",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 8,
    bikeScore: 36,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.realtor.com/realestateandhomes-detail/10272-Whitetail-Cir_Fishers_IN_46037_M31114-82830",
    notes: "Windermere golf community.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 192,
    imageUrl:
      "https://ap.rdcpix.com/81fb77bb2d114fa4a445c4efb076fe09l-m3444053804rd-w1280_h960.webp",
    latitude: 39.93710973008341,
    longitude: -85.98644956200211,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: false,
      restaurants: false,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 34,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2025-10-15",
  },

  {
    id: "prop_009",
    address: "10747 Red Pine Dr",
    city: "Fishers",
    price: 475000,
    beds: 5,
    baths: 3.5,
    sqft: 4323,
    garage: 2,
    yearBuilt: 2000,
    hoaAnnual: 0,
    lotSize: 0.32,
    basement: "Finished",
    neighborhood: "Pine Bluff Overlook",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 15,
    bikeScore: 47,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.zillow.com/homedetails/10747-Red-Pine-Dr-Fishers-IN-46037/73228273_zpid/",
    notes:
      "5 bedroom home with finished basement. Near Windermere golf course.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 110,
    imageUrl:
      "https://photos.zillowstatic.com/fp/025cf54831f2bcfc22eca5aac5dda275-cc_ft_1152.webp",
    latitude: 39.94267103088205,
    longitude: -85.99661627734538,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: false,
      restaurants: false,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 37,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2025-10-15",
  },

  {
    id: "prop_010",
    address: "11987 Bird Key Blvd",
    city: "Fishers",
    price: 578000,
    beds: 4,
    baths: 3.5,
    sqft: 3618,
    garage: 2,
    yearBuilt: 2004,
    hoaAnnual: 0,
    lotSize: 0.27,
    basement: "Finished",
    neighborhood: "Rolling Knoll",
    schools: "Hamilton Southeastern",
    commuteHusband: 35,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 14,
    bikeScore: 53,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.redfin.com/IN/Fishers/11987-Bird-Key-Blvd-46037/home/67069901",
    notes: "Brick home with finished basement.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 161,
    imageUrl:
      "https://ssl.cdn-redfin.com/photo/147/bigphoto/902/22082902_0.jpg",
    latitude: 39.96291071302564,
    longitude: -85.969532246657,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 52,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2025-10-15",
  },

  {
    id: "prop_012",
    address: "12997 Bartlett Dr",
    city: "Fishers",
    price: 474900,
    beds: 5,
    baths: 3,
    sqft: 4042,
    garage: 3,
    yearBuilt: 2007,
    hoaAnnual: 610,
    lotSize: 0.23,
    basement: "None",
    neighborhood: "Tanglewood",
    schools: "Hamilton Southeastern",
    commuteHusband: 32,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 12,
    bikeScore: 54,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.coldwellbanker.com/in/fishers/12997-bartlett-dr/lid-P00800000H6ED3vKMeR9spQTFxALNPsGllH5ErFv",
    notes: "Large 5BR home in Tanglewood.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2025-10-15", price: 479900, event: "Listed" }],
    favorite: false,
    pricePerSqft: 119,
    imageUrl:
      "https://images-listings.coldwellbanker.com/IN_MIBOR/22/08/34/80/_P/22083480_P00.jpg",
    latitude: 39.985,
    longitude: -86.0125,
    amenities: {
      parks: true,
      trails: false,
      shopping: true,
      restaurants: true,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 156,
      lastPriceChange: null,
      priceChanges: [],
      views: 1069,
    },
    listingDate: "2026-02-12",
  },

  {
    id: "prop_014",
    address: "10480 Creektree Ln",
    city: "Fishers",
    price: 600000,
    beds: 4,
    baths: 3,
    sqft: 4217,
    garage: 3,
    yearBuilt: 2003,
    hoaAnnual: 0,
    lotSize: 0.29,
    basement: "Unknown",
    neighborhood: "Anderson Hall",
    schools: "Hamilton Southeastern",
    commuteHusband: 40,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 8,
    bikeScore: 53,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.realtor.com/realestateandhomes-detail/10480-Creektree-Ln_Fishers_IN_46038_M31071-14492",
    notes: "Recently listed Anderson Hall home.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 142,
    imageUrl:
      "https://cflare.smarteragent.com/rest/Resizer?sig_id=69&quality=0.8&url=https://storage.googleapis.com/slp5-stream-listing-media-prod/MLSGrid/190/22068876/photo/media/0_4261413115053874048.jpg&width=1000",
    latitude: 39.983606286476395,
    longitude: -85.98258444665584,
    coordinateVerified: true, // Verified via whereorg.com + MLS data on 2026-03-19
    coordinateVerified: true, // ✅ Verified from whereorg.com + MLS data (March 19, 2026)
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: false,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 5,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-02-23",
  },

  {
    id: "prop_015",
    address: "10236 Bent Tree Ln",
    city: "Fishers",
    price: 619900,
    beds: 4,
    baths: 2.5,
    sqft: 4209,
    garage: 3,
    yearBuilt: 1995,
    hoaAnnual: 0,
    lotSize: 0.31,
    basement: "Finished",
    neighborhood: "Woods Edge At Windermere",
    schools: "Hamilton Southeastern",
    commuteHusband: 38,
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 13,
    bikeScore: 37,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.schulerbauer.com/in/fishers/10236-bent-tree-ln-46037/listing/13686529/",
    notes: "Holiday lights street home.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 147,
    imageUrl:
      "https://cdn.listingphotos.sierrastatic.com/pics3x/v1772489899/203/203_22082152_01.jpg",
    latitude: 39.936641852261445,
    longitude: -85.98868479083804,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: false,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 2,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-02-01",
  },

  {
    id: "prop_016",
    address: "12033 Flintstone Ct",
    city: "Fishers",
    price: 510000,
    beds: 5,
    baths: 3,
    sqft: 3382,
    garage: 2,
    yearBuilt: 2000,
    hoaAnnual: 0,
    lotSize: 0.24,
    basement: "Finished",
    neighborhood: "Sandstone Lakes",
    schools: "Hamilton Southeastern",
    commuteHusband: 35,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 29,
    bikeScore: 59,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.zillow.com/homedetails/12033-Flint-Stone-Ct-Fishers-IN-46037/73274763_zpid/",
    notes: "Move-in ready Sandstone Lakes home.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 151,
    imageUrl:
      "https://photos.talktotucker.com/medium/mibor/22087220/12033-flint-stone-court-fishers-46037-ccb528d0-b8b7-4b83-ba0b-dfa5c931ccb8-0.jpeg",
    latitude: 39.96388970331086,
    longitude: -85.94847674665694,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: false,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-06",
  },

  {
    id: "prop_017",
    address: "9943 Deering St",
    city: "Fishers",
    price: 499000,
    beds: 4,
    baths: 2.5,
    sqft: 3830,
    garage: 2,
    yearBuilt: 1996,
    hoaAnnual: 0,
    lotSize: 0.27,
    basement: "Partial",
    neighborhood: "Spyglass Hill",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 15,
    bikeScore: 57,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.redfin.com/IN/Fishers/9943-Deering-St-46037/home/67060274",
    notes: "Spyglass Hill home built in 1996.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 130,
    imageUrl:
      "https://ssl.cdn-redfin.com/photo/147/bigphoto/523/22088523_0.jpg",
    latitude: 39.94736887365393,
    longitude: -85.99192700432972,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: false,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-07",
  },

  {
    id: "prop_018",
    address: "13374 Landwood Dr",
    city: "Fishers",
    price: 640000,
    beds: 4,
    baths: 3.5,
    sqft: 4276,
    garage: 3,
    yearBuilt: 2000,
    hoaAnnual: 0,
    lotSize: 0.28,
    basement: "Finished",
    neighborhood: "Links at Gray Eagle",
    schools: "Hamilton Southeastern",
    commuteHusband: 36,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 12,
    bikeScore: 52,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.realtor.com/realestateandhomes-detail/13374-Landwood-Dr_Fishers_IN_46037_M37000-52903",
    notes: "Gray Eagle golf community home.",
    pros: [],
    cons: [],
    priceHistory: [
      { date: "2026-03-13", price: 640000, event: "Listed" },
      { date: "2020-01-21", price: 387400, event: "Sold" },
    ],
    favorite: false,
    pricePerSqft: 150,
    imageUrl:
      "https://photos.talktotucker.com/medium/mibor/22088967/13374-landwood-drive-fishers-46037-0bb02b16-c500-4264-9e68-ec4d35ad4c26-0.jpeg",
    latitude: 39.96223066123813,
    longitude: -85.92545233131347,
    coordinateVerified: false,
    coordinateVerified: false, // Needs Google Maps verification
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: false,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-13",
  },

  {
    id: "prop_019",
    address: "11008 Stratford Way",
    city: "Fishers",
    price: 499900,
    beds: 4,
    baths: 2.5,
    sqft: 3138,
    garage: 2,
    yearBuilt: 1992,
    hoaAnnual: 546,
    lotSize: 0.27,
    basement: "Finished",
    neighborhood: "Oxford Park",
    schools: "Hamilton Southeastern",
    commuteHusband: 32, // Manual verification recommended
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 9,
    bikeScore: 54,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.realtor.com/realestateandhomes-detail/11008-Stratford-Way_Fishers_IN_46038_M33380-63613",
    notes:
      "4-season room, finished basement with 30x20 playroom. Listed 9 days.",
    pros: [],
    cons: [],
    priceHistory: [{ date: "2026-03-09", price: 499900, event: "Listed" }],
    favorite: false,
    pricePerSqft: 159,
    imageUrl:
      "https://ap.rdcpix.com/d32bcc1af93adb290455af9f238ef150l-m1205120643rd-w960_h720.webp",
    latitude: 39.947588248037,
    longitude: -86.05841686200147,
    amenities: {
      parks: true,
      trails: true,
      shopping: false,
      restaurants: false,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 9,
      lastPriceChange: null,
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-09",
  },
  {
    id: "prop_020",
    address: "10970 Andrews Pl",
    city: "Fishers",
    price: 580000,
    beds: 5,
    baths: 4,
    sqft: 4316,
    garage: 2,
    yearBuilt: 1995,
    hoaAnnual: 710,
    lotSize: 0.31,
    basement: "Finished",
    neighborhood: "Walnut Creek",
    schools: "Hamilton Southeastern",
    commuteHusband: 34,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 12,
    bikeScore: 53,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.redfin.com/IN/Fishers/10970-Andrews-Pl-46037/home/82381126",
    notes: "Corner lot in Walnut Creek with finished basement.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 134,
    imageUrl:
      "https://photos.talktotucker.com/medium/mibor/22089401/10970-andrews-place-fishers-46037-f55b4e71-b410-4df8-afd3-31606ac3fdd2-0.jpeg",
    latitude: 39.947017,
    longitude: -85.998194,
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: "",
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-18",
  },
  {
    id: "prop_021",
    address: "11750 Belle Plaine Blvd",
    city: "Fishers",
    price: 650000,
    beds: 4,
    baths: 4,
    sqft: 4136,
    garage: 2,
    yearBuilt: 2001,
    hoaAnnual: 750,
    lotSize: 0.47,
    basement: "Finished",
    neighborhood: "Rolling Knoll",
    schools: "Hamilton Southeastern",
    commuteHusband: 34,
    status: "Pending",
    daysOnMarket: "Active",
    walkScore: 15,
    bikeScore: 59,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.remax.com/luxury/in/fishers/home-details/11750-belle-plaine-blvd-fishers-in-46037/2098614118895711227/M00000255/22089911",
    notes: "Premium corner lot on nearly half an acre in Rolling Knoll.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 157,
    imageUrl:
      "https://images.remax.com/webapi-properties-mibor3/6401ccbfca979759a6af7faf9ca49e15d85886e9-3-original.jpeg",
    latitude: 39.959441810293235,
    longitude: -85.9691714908367,
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: "",
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-19",
  },
  {
    id: "prop_022",
    address: "12992 Minden Dr",
    city: "Fishers",
    price: 575000,
    beds: 5,
    baths: 4,
    sqft: 4346,
    garage: 2,
    yearBuilt: 2011,
    hoaAnnual: 650,
    lotSize: 0.21,
    basement: "Finished",
    neighborhood: "Saxony",
    schools: "Hamilton Southeastern",
    commuteHusband: 33,
    status: "Pending",
    daysOnMarket: "New",
    walkScore: 27,
    bikeScore: 59,
    hasNeighborhoodPool: true,
    zillowLink:
      "https://www.redfin.com/IN/Fishers/12992-Minden-Dr-46037/home/107057384",
    notes:
      "Walkable to community pool, 2 playgrounds, Witten Park, trails, Saxony Pizzeria & Boom Town Donuts. Recently updated with new staircase, carpet (March 2026), new appliances, new roof (2020).",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 132,
    imageUrl:
      "https://photos.talktotucker.com/medium/mibor/22087784/12992-minden-drive-fishers-46037-3d2001ae-1f75-4dce-a851-e64626860522-0.jpeg",
    latitude: 39.97947421767583,
    longitude: -85.92583729083555,
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: true,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: "",
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-19",
  },
  {
    id: "prop_023",
    address: "14211 Monarchy Ln",
    city: "Fishers",
    price: 535000,
    beds: 4,
    baths: 4,
    sqft: 3909,
    garage: 3,
    yearBuilt: 2003,
    hoaAnnual: 500,
    lotSize: 0.25,
    basement: "Finished",
    neighborhood: "Royalwood South",
    schools: "Hamilton Southeastern",
    commuteHusband: 31,
    status: "Pending",
    daysOnMarket: "New",
    walkScore: 44,
    bikeScore: 68,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.remax.com/luxury/in/fishers/home-details/14211-monarchy-ln-fishers-in-46037/10805835208956337848/M00000255/22088607",
    notes:
      "Backs to nature preserve with access to Geist-Greenway. Finished basement with 9-ft ceilings, rec room with bar, Murphy bed in guest room. Outdoor entertaining with pergola deck, stamped concrete patio, built-in gas firepit & grill.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 137,
    imageUrl:
      "https://images.remax.com/webapi-properties-mibor3/1f154c9422ded61447244cf10db9260dec536cc6-3-original.jpeg",
    latitude: 39.959724914832016,
    longitude: -85.91110298898539,
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 1,
      lastPriceChange: "",
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-20",
  },
  {
    id: "prop_024",
    address: "9767 Fortune Dr",
    city: "Fishers",
    price: 650000,
    beds: 4,
    baths: 3.5,
    sqft: 4340,
    garage: 3,
    yearBuilt: 1995,
    hoaAnnual: 300, // Based on other Walnut Creek properties
    lotSize: 0.42,
    basement: "Finished", // Typical for Walnut Creek custom homes
    neighborhood: "Walnut Creek",
    schools: "Hamilton Southeastern",
    commuteHusband: 33, // Estimated based on Cumberland Rd access
    status: "Active",
    daysOnMarket: "Active",
    walkScore: 5,
    bikeScore: 45,
    hasNeighborhoodPool: false,
    zillowLink:
      "https://www.redfin.com/IN/Fishers/9767-Fortune-Dr-46037/home/67063879",
    notes: "Large lot with mature trees in Walnut Creek.",
    pros: [],
    cons: [],
    priceHistory: [],
    favorite: false,
    pricePerSqft: 150,
    imageUrl:
      "https://ssl.cdn-redfin.com/photo/147/bigphoto/129/22087129_0.jpg",
    latitude: 39.945815340643925,
    longitude: -85.99641988805293,
    coordinateVerified: true,
    amenities: {
      parks: true,
      trails: true,
      shopping: true,
      restaurants: true,
      communityEvents: false,
    },
    history: {
      daysOnMarket: 24, // Listed Mar 4, 2026 (24 days ago as of Mar 28)
      lastPriceChange: "",
      priceChanges: [],
      views: 0,
    },
    listingDate: "2026-03-04",
  },
];
